#!/bin/bash

# stash - A simple wrapper around stow and git for managing dotfiles
#
# https://github.com/scotte/stash

set -eu

STASH=~/stash
PACKAGE=stow
TARGET=~
HOST=$(hostname -s)

usage() {
    echo "$@"
    exit 1
}

[[ -d $STASH/$PACKAGE ]] || usage "ERROR: $STASH/$PACKAGE does not exist"
cd $STASH/$PACKAGE

[[ $(git branch --list $HOST) ]] || git checkout -b $HOST
git diff --quiet || git commit -a
git rebase master
stow -v1 -d $STASH -t $TARGET $PACKAGE

exit 0
