#!/bin/bash

# stash - A simple wrapper around stow and git for managing dotfiles
#
# https://github.com/scotte/stash
#
# stash is licensed under GPLv3. See the LICENSE file for additional details.

set -eu

STASH=~/stash
PACKAGE=stow
TARGET=~
HOST=$(hostname -s)

error() {
    echo "$@"
    exit 1
}

[[ -d $STASH/$PACKAGE ]] || error "ERROR: $STASH/$PACKAGE does not exist"
cd $STASH/$PACKAGE

[[ $(git branch --list $HOST) ]] && git checkout $HOST || git checkout -b $HOST
git diff --quiet || git commit -a
git rebase master
stow --verbose=1 --dir=$STASH --target=$TARGET --ignore=".*\.orig$" $PACKAGE

exit 0
